<?php

/**
 * @file
 * Contains islandora_collection hook implementations.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_collection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_collection module.
    case 'help.page.islandora_collection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Islandora Collection') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_node_view_alter().
 */
function islandora_collection_node_view_alter(&$build, EntityInterface $entity) {
  \Drupal::service('islandora_collection.view_alter.collection_link_header')
    ->alter($build, $entity);
}
